# Generated by Django 3.0.8 on 2020-08-14 16:45

import cpf_field.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comuns', '0003_pessoa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='id',
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='cpf',
            field=cpf_field.models.CPFField(max_length=14, primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcao', models.CharField(max_length=50)),
                ('cpf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comuns.Pessoa')),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comuns.Departamento')),
            ],
        ),
    ]
