# Generated by Django 3.0.8 on 2020-08-14 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comuns', '0005_auto_20200814_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cpf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comuns.Pessoa'),
        ),
    ]
