# Generated by Django 3.0.8 on 2020-08-14 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comuns', '0006_auto_20200814_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='id',
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cpf',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='comuns.Pessoa'),
        ),
    ]
