# Generated by Django 3.0.5 on 2020-04-13 14:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('subcategoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='categoria', to='controles.Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id_item', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('caracteristica', models.TextField(blank=True, max_length=200, null=True)),
                ('marca', models.CharField(max_length=30)),
                ('modelo', models.CharField(max_length=30)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('local', models.CharField(blank=True, max_length=50, null=True)),
                ('status_disponivel', models.BooleanField(default=True)),
                ('status_manutencao', models.BooleanField(default=False)),
                ('status_emprestado', models.BooleanField(default=False)),
                ('tipo_consumivel', models.BooleanField(default=False)),
                ('quantidade', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999)])),
                ('validade', models.DateField(blank=True, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='controles.Categoria')),
                ('id_departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='controles.Departamento')),
                ('id_equipamento_pertencente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='item', to='controles.Item')),
            ],
            options={
                'verbose_name_plural': 'Itens',
            },
        ),
        migrations.CreateModel(
            name='Manual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('documento', models.FileField(upload_to='uploads/manual/')),
            ],
            options={
                'verbose_name_plural': 'manuais',
            },
        ),
        migrations.CreateModel(
            name='NotaFiscal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('documento', models.FileField(upload_to='uploads/notafiscal/')),
            ],
            options={
                'verbose_name_plural': 'notas fiscais',
            },
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('acronimo', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id_item', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='controles.Item')),
                ('patrimonio_itti', models.CharField(blank=True, default='', max_length=30, null=True, unique=True)),
                ('patrimonio_ufpr', models.IntegerField(blank=True, default=0, null=True, unique=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999)])),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='id_notafiscal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='controles.NotaFiscal'),
        ),
        migrations.AddField(
            model_name='item',
            name='projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='controles.Projeto'),
        ),
    ]
