# Generated by Django 3.0.5 on 2020-04-15 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='subcategoria',
        ),
    ]
