# Generated by Django 3.0.5 on 2020-04-15 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controles', '0003_subcategoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategoria',
            old_name='id_categoria',
            new_name='categoria',
        ),
    ]
