# Generated by Django 2.2.2 on 2020-07-16 17:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controles', '0005_auto_20200716_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='patrimonio_ufpr',
            field=models.IntegerField(blank=True, null=True, unique=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999)]),
        ),
    ]
