# Generated by Django 2.2.2 on 2020-07-16 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controles', '0006_auto_20200716_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='id_manual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='controles.Manual'),
        ),
    ]
