# Generated by Django 2.2.2 on 2020-07-21 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controles', '0007_equipamento_id_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='subcategoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='controles.Subcategoria'),
        ),
    ]
