# Generated by Django 2.2.2 on 2020-07-28 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controles', '0008_item_subcategoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='id_equipamento_pertencente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item', to='controles.Item'),
        ),
    ]
