# Generated by Django 2.2.2 on 2020-07-30 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controles', '0009_auto_20200728_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='id_departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='comuns.Departamento'),
        ),
        migrations.DeleteModel(
            name='Departamento',
        ),
    ]
