# Generated by Django 2.2.2 on 2020-07-30 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controles', '0010_auto_20200730_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comuns.Projeto'),
        ),
        migrations.DeleteModel(
            name='Projeto',
        ),
    ]
