# Generated by Django 2.2.2 on 2020-07-31 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controles', '0013_auto_20200730_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='id_manual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='controles.Manual'),
        ),
    ]
