# Generated by Django 3.0.8 on 2020-08-10 15:32

import controles.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controles', '0016_categoria_abreviacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='ano',
            field=models.PositiveIntegerField(default=2020, validators=[django.core.validators.MinValueValidator(2009), controles.models.max_value_current_year]),
        ),
    ]
