# Generated by Django 3.0.8 on 2020-08-14 17:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('comuns', '0004_auto_20200814_1345'),
        ('controles', '0017_item_ano'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emprestimo', models.DateField(default=django.utils.timezone.now)),
                ('cpf', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comuns.Pessoa')),
                ('id_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='controles.Item')),
            ],
        ),
    ]
