# Generated by Django 3.0.8 on 2020-08-14 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controles', '0021_auto_20200814_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimo',
            name='cpf_func',
        ),
    ]
