# Generated by Django 3.0.8 on 2020-08-14 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controles', '0022_remove_emprestimo_cpf_func'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devolucao',
            name='id',
        ),
        migrations.AlterField(
            model_name='devolucao',
            name='emprestimo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='controles.Emprestimo'),
        ),
    ]
