# Generated by Django 3.0.8 on 2020-08-14 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controles', '0025_auto_20200814_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devolucao',
            name='cpf_func',
        ),
        migrations.RemoveField(
            model_name='devolucao',
            name='data_devolucao',
        ),
        migrations.RemoveField(
            model_name='devolucao',
            name='laudo',
        ),
    ]
