# Generated by Django 3.0.8 on 2020-08-14 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comuns', '0007_auto_20200814_1531'),
        ('controles', '0026_auto_20200814_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='devolucao',
            name='cpf_func',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='comuns.Funcionario'),
            preserve_default=False,
        ),
    ]
