# Generated by Django 3.0.8 on 2020-08-14 20:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('controles', '0028_auto_20200814_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='devolucao',
            name='data_devolucao',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='devolucao',
            name='laudo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='controles.Laudo'),
            preserve_default=False,
        ),
    ]
