# Generated by Django 3.0.8 on 2020-08-14 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controles', '0029_auto_20200814_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devolucao',
            name='laudo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='controles.Laudo'),
        ),
    ]
