# Generated by Django 3.0.8 on 2020-08-14 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controles', '0030_auto_20200814_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devolucao',
            name='emprestimo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='controles.Emprestimo'),
        ),
    ]
